cache:
    paths:
        - .yarn
        - node_modules/

before_script:
    - yarn install --cache-folder .yarn

stages:
    - lint
    - lint_doc
    - check_types
    - test
    - build_deploy
    - code_analysis

code_quality:
    stage: lint
    script:
        - yarn lint
    only:
        - merge_requests

check_types:
    stage: check_types
    script:
        - yarn check-types
    only:
        - merge_requests

test:
    stage: test
    script:
        - yarn test
    only:
        - merge_requests
        - dev

doc_quality:
    stage: lint_doc
    script:
        - yarn lint-doc
    only:
        - /doc(s)|release/
        - master

build_deploy:
    stage: build_deploy
    script:
        - yarn build
    only:
        - dev

code_analysis:
    stage: code_analysis
    script:
        - yarn sonar
    only:
        - dev
