/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dtstack.engine.domain;


import com.baomidou.mybatisplus.annotation.TableName;

import java.io.Serializable;
import java.util.Date;

/**
 * company: www.dtstack.com
 * author: toutian
 * create: 2019/10/22
 */
@TableName("schedule_task_shade")
public class ScheduleTask implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.tenant_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.name
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.task_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.engine_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer engineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.compute_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer computeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.task_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.schedule_conf
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String scheduleConf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.period_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer periodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.schedule_status
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer scheduleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.gmt_create
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.gmt_modified
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.modify_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.create_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.version_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.is_deleted
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.task_desc
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String taskDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.flow_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private Integer flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.component_version
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String componentVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.business_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.extra_info
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private String extraInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task_shade.owner_user_id
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_task_shade
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.id
     *
     * @return the value of schedule_task_shade.id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.id
     *
     * @param id the value for schedule_task_shade.id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.tenant_id
     *
     * @return the value of schedule_task_shade.tenant_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.tenant_id
     *
     * @param tenantId the value for schedule_task_shade.tenant_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.name
     *
     * @return the value of schedule_task_shade.name
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.name
     *
     * @param name the value for schedule_task_shade.name
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.task_type
     *
     * @return the value of schedule_task_shade.task_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.task_type
     *
     * @param taskType the value for schedule_task_shade.task_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.engine_type
     *
     * @return the value of schedule_task_shade.engine_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getEngineType() {
        return engineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.engine_type
     *
     * @param engineType the value for schedule_task_shade.engine_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setEngineType(Integer engineType) {
        this.engineType = engineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.compute_type
     *
     * @return the value of schedule_task_shade.compute_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getComputeType() {
        return computeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.compute_type
     *
     * @param computeType the value for schedule_task_shade.compute_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setComputeType(Integer computeType) {
        this.computeType = computeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.task_id
     *
     * @return the value of schedule_task_shade.task_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.task_id
     *
     * @param taskId the value for schedule_task_shade.task_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.schedule_conf
     *
     * @return the value of schedule_task_shade.schedule_conf
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getScheduleConf() {
        return scheduleConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.schedule_conf
     *
     * @param scheduleConf the value for schedule_task_shade.schedule_conf
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setScheduleConf(String scheduleConf) {
        this.scheduleConf = scheduleConf == null ? null : scheduleConf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.period_type
     *
     * @return the value of schedule_task_shade.period_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.period_type
     *
     * @param periodType the value for schedule_task_shade.period_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setPeriodType(Integer periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.schedule_status
     *
     * @return the value of schedule_task_shade.schedule_status
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getScheduleStatus() {
        return scheduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.schedule_status
     *
     * @param scheduleStatus the value for schedule_task_shade.schedule_status
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setScheduleStatus(Integer scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.gmt_create
     *
     * @return the value of schedule_task_shade.gmt_create
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.gmt_create
     *
     * @param gmtCreate the value for schedule_task_shade.gmt_create
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.gmt_modified
     *
     * @return the value of schedule_task_shade.gmt_modified
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.gmt_modified
     *
     * @param gmtModified the value for schedule_task_shade.gmt_modified
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.modify_user_id
     *
     * @return the value of schedule_task_shade.modify_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.modify_user_id
     *
     * @param modifyUserId the value for schedule_task_shade.modify_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.create_user_id
     *
     * @return the value of schedule_task_shade.create_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.create_user_id
     *
     * @param createUserId the value for schedule_task_shade.create_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.version_id
     *
     * @return the value of schedule_task_shade.version_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.version_id
     *
     * @param versionId the value for schedule_task_shade.version_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.is_deleted
     *
     * @return the value of schedule_task_shade.is_deleted
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.is_deleted
     *
     * @param isDeleted the value for schedule_task_shade.is_deleted
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.task_desc
     *
     * @return the value of schedule_task_shade.task_desc
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.task_desc
     *
     * @param taskDesc the value for schedule_task_shade.task_desc
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.flow_id
     *
     * @return the value of schedule_task_shade.flow_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.flow_id
     *
     * @param flowId the value for schedule_task_shade.flow_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.component_version
     *
     * @return the value of schedule_task_shade.component_version
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getComponentVersion() {
        return componentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.component_version
     *
     * @param componentVersion the value for schedule_task_shade.component_version
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setComponentVersion(String componentVersion) {
        this.componentVersion = componentVersion == null ? null : componentVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.business_type
     *
     * @return the value of schedule_task_shade.business_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.business_type
     *
     * @param businessType the value for schedule_task_shade.business_type
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task_shade.extra_info
     *
     * @return the value of schedule_task_shade.extra_info
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public String getExtraInfo() {
        return extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.extra_info
     *
     * @param extraInfo the value for schedule_task_shade.extra_info
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo == null ? null : extraInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.extra_info
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task_shade.extra_info
     *
     * @param ownerUserId the value for schedule_task_shade.owner_user_id
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_shade
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", name=").append(name);
        sb.append(", taskType=").append(taskType);
        sb.append(", engineType=").append(engineType);
        sb.append(", computeType=").append(computeType);
        sb.append(", taskId=").append(taskId);
        sb.append(", scheduleConf=").append(scheduleConf);
        sb.append(", periodType=").append(periodType);
        sb.append(", scheduleStatus=").append(scheduleStatus);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", modifyUserId=").append(modifyUserId);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", versionId=").append(versionId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", taskDesc=").append(taskDesc);
        sb.append(", flowId=").append(flowId);
        sb.append(", componentVersion=").append(componentVersion);
        sb.append(", businessType=").append(businessType);
        sb.append(", extraInfo=").append(extraInfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_shade
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduleTaskShade other = (ScheduleTaskShade) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
                && (this.getEngineType() == null ? other.getEngineType() == null : this.getEngineType().equals(other.getEngineType()))
                && (this.getComputeType() == null ? other.getComputeType() == null : this.getComputeType().equals(other.getComputeType()))
                && (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
                && (this.getScheduleConf() == null ? other.getScheduleConf() == null : this.getScheduleConf().equals(other.getScheduleConf()))
                && (this.getPeriodType() == null ? other.getPeriodType() == null : this.getPeriodType().equals(other.getPeriodType()))
                && (this.getScheduleStatus() == null ? other.getScheduleStatus() == null : this.getScheduleStatus().equals(other.getScheduleStatus()))
                && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
                && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
                && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()))
                && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
                && (this.getVersionId() == null ? other.getVersionId() == null : this.getVersionId().equals(other.getVersionId()))
                && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
                && (this.getTaskDesc() == null ? other.getTaskDesc() == null : this.getTaskDesc().equals(other.getTaskDesc()))
                && (this.getFlowId() == null ? other.getFlowId() == null : this.getFlowId().equals(other.getFlowId()))
                && (this.getComponentVersion() == null ? other.getComponentVersion() == null : this.getComponentVersion().equals(other.getComponentVersion()))
                && (this.getBusinessType() == null ? other.getBusinessType() == null : this.getBusinessType().equals(other.getBusinessType()))
                && (this.getExtraInfo() == null ? other.getExtraInfo() == null : this.getExtraInfo().equals(other.getExtraInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task_shade
     *
     * @mbg.generated Mon Dec 06 12:34:57 UTC 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getEngineType() == null) ? 0 : getEngineType().hashCode());
        result = prime * result + ((getComputeType() == null) ? 0 : getComputeType().hashCode());
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getScheduleConf() == null) ? 0 : getScheduleConf().hashCode());
        result = prime * result + ((getPeriodType() == null) ? 0 : getPeriodType().hashCode());
        result = prime * result + ((getScheduleStatus() == null) ? 0 : getScheduleStatus().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getVersionId() == null) ? 0 : getVersionId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getTaskDesc() == null) ? 0 : getTaskDesc().hashCode());
        result = prime * result + ((getFlowId() == null) ? 0 : getFlowId().hashCode());
        result = prime * result + ((getComponentVersion() == null) ? 0 : getComponentVersion().hashCode());
        result = prime * result + ((getBusinessType() == null) ? 0 : getBusinessType().hashCode());
        result = prime * result + ((getExtraInfo() == null) ? 0 : getExtraInfo().hashCode());
        return result;
    }
}
