version: '3'
services:
  taier-db:
    image: dtopensource/taier-mysql:latest
    environment:
      MYSQL_DATABASE: taier
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
  taier-zk:
    image: zookeeper:3.4.9
  taier:
    image: dtopensource/taier:latest
    environment:
      ZK_HOST: taier-zk
      ZK_PORT: 2181
      DB_HOST: taier-db
      DB_PORT: 3306
      DB_ROOT: root
      DB_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 8090:8090