version: '3'
services:
  taier-db:
    image: taige/mysql:1.10
#    ports:
#      - 3306:3306
    environment:
      MYSQL_DATABASE: taier
      MYSQL_ROOT_PASSWORD: 123456
  taier-zk:
    image: zookeeper:3.4.9
  taier-ui:
    image: taier-ui:1.10
    ports:
      - 80:80
    environment:
      TAIER_IP: taier
  taier:
    image: taier:1.10
#    ports:
#      - 8090:8090
    environment:
      NODE_ZKADDRESS: taier-zk
      MYSQL_IP: taier-db