INSERT INTO schedule_dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, gmt_create, gmt_modified, is_deleted) VALUES ('hadoop_config', 'HDP 3.1.x', '-201', '', 5, 0, 'LONG', 'YARN', 0, '2021-02-05 11:53:21', '2021-02-05 11:53:21', 0);
INSERT INTO schedule_dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, gmt_create, gmt_modified, is_deleted) VALUES ('hadoop_config', 'CDH 6.2.x', '-202', '', 5, 0, 'LONG', 'YARN', 0, '2021-02-05 11:53:21', '2021-02-05 11:53:21', 0);
INSERT INTO schedule_dict (dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, gmt_create, gmt_modified, is_deleted) VALUES ('hadoop_config', 'CDP 7.1.x', '-203', '', 5, 0, 'LONG', 'YARN', 0, '2021-02-05 11:53:21', '2021-02-05 11:53:21', 0);


INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -201, 1, 'CUSTOM_CONTROL', 1, 'hdp.version', '3.1.4.0-315', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -201, 1, 'CUSTOM_CONTROL', 1, 'yarn.application.classpath', '$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -201, 1, 'CUSTOM_CONTROL', 1, 'mapreduce.application.classpath', '$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -202, 1, 'CUSTOM_CONTROL', 1, 'yarn.application.classpath', '$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -202, 1, 'CUSTOM_CONTROL', 1, 'mapreduce.application.classpath', '$PWD/mr-framework/*,$MR2_CLASSPATH,/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/*,$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -203, 1, 'CUSTOM_CONTROL', 1, 'yarn.application.classpath', '$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);
INSERT INTO console_component_config (cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES (-2, -203, 1, 'CUSTOM_CONTROL', 1, 'mapreduce.application.classpath', '$PWD/mr-framework/*,$MR2_CLASSPATH,/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/*,$HADOOP_CLIENT_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_MAPRED_HOME/*', null, null, null, null, '2021-03-05 14:48:18', '2021-03-05 14:48:18', 0);