INSERT OVERWRITE TABLE dwd.dwd_center_paylog_di partition(etl_date='${etl_date}')
SELECT
    addtimes,
    userid,
    appid,
    case when  gameid=627 then 618 else gameid end as t1,
    orderamount,
    paymentamount,
    purchaseyunbi,
    commodityid,
    rechargetype,
    ordernumber,
    threeordernumber,
    orderstatus,
    paymenttimes,
    sendtimes,
    clientipaddress,
    c2,
    c3,
    c4,
    clientdeviceid,
    clientversion,
    spareparameter6[0],
    spareparameter6[1],
    spareparameter1,
    spareparameter2,
    spareparameter3,
    spareparameter4,
    spareparameter5,
    spareparameter6,
    spareparameter7,
    spareparameter8,
    loginname,
    hostname
from (select
addtimes,
userid,
appid,
gameid,
orderamount,
paymentamount,
purchaseyunbi,
commodityid,
rechargetype,
ordernumber,
threeordernumber,
orderstatus,
paymenttimes,
sendtimes,
clientipaddress,
clientdeviceid,
clientversion,
spareparameter1,
spareparameter2,
spareparameter3,
spareparameter4,
spareparameter5,
spareparameter6,
spareparameter7,
spareparameter8,
loginname,
hostname,
etl_date
from ods.ods_t_rechargeorderrecord_di where etl_date='2020-09-14'
union all
select addtimes,
userid,
appid,
gameid,
orderamount,
paymentamount,
purchaseyunbi,
'-520' as commodityid,
rechargetype,
ordernumber,
threeordernumber,
orderstatus,
paymenttimes,
null sendtimes,
clientipaddress,
clientdeviceid,
clientversion,
tradertype as spareparameter1,
companyid as spareparameter2,
userpayaccount as spareparameter3,
merchantaccount as spareparameter4,
extraparameter as spareparameter5,
spareparameter3 as spareparameter6,
spareparameter1 as spareparameter7,
case when RechargeType=18 then 'EUnHyZJQc9ikWbXhoP57vA==' else SpareParameter4 end  as spareparameter8,
loginname,
hostname,
etl_date
 from ods.ods_t_yunbiorderrecord_di  where etl_date='${etl_date}'
)t
lateral view ipexplode(nvl(clientipaddress,'0.0.0.0')) ipTable as  c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11;