-- Doris数据源
INSERT INTO `dsc_type` (`data_type`, `data_classify_id`, `weight`, `img_url`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `sorted`, `invisible`) VALUES ('Doris', 7, 0, 'Doris.png', 0, '2021-07-06 12:22:10', '2021-07-06 15:49:09', 0, 0, 1200, 0);
-- Doris数据源版本
INSERT INTO `dsc_version` ( `data_type`, `data_version`, `sorted`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`) VALUES ( 'Doris', '0.14.x', 0, 0, '2021-07-06 14:49:27', '2021-07-06 14:49:42', 0, 0);
-- Doris授权给实时
INSERT INTO `dsc_app_mapping` ( `app_type`, `data_type`, `data_version`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`) VALUES ( 7, 'Doris', '0.14.x', 0, '2021-07-06 13:49:00', '2021-07-06 13:49:00', 0, 0);
-- Doris表单
INSERT INTO `dsc_form_field` ( `name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'jdbcUrl', 'JDBC URL', 'Input', 1, 0, NULL, NULL, NULL, 1, '{\"regex\":{\"message\":\"JDBC URL格式不符合规则!\"}}', '示例：jdbc:mysql://host:3306/dbName', NULL, '/jdbc:mysql:\\/\\/(.)+/', 0, '2021-07-06 09:35:57', '2021-07-06 16:07:17', 0, 0, 'Doris-0.14.x', '');
INSERT INTO `dsc_form_field` ( `name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'username', '用户名', 'Input', 0, 0, NULL, NULL, NULL, 1, '', NULL, NULL, NULL, 0, '2021-07-06 09:35:57', '2021-07-06 10:08:08', 0, 0, 'Doris-0.14.x', '');
INSERT INTO `dsc_form_field` ( `name`, `label`, `widget`, `required`, `invisible`, `default_value`, `place_hold`, `request_api`, `is_link`, `valid_info`, `tooltip`, `style`, `regex`, `is_deleted`, `gmt_create`, `gmt_modified`, `create_user_id`, `modify_user_id`, `type_version`, `options`) VALUES ( 'password', '密码', 'Password', 0, 0, NULL, NULL, NULL, 0, '', NULL, NULL, NULL, 0, '2021-07-06 09:35:57', '2021-07-06 10:08:12', 0, 0, 'Doris-0.14.x', '');
