package com.dtstack.engine.api.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * @Auther: dazhi
 * @Date: 2021/3/5 10:37 上午
 * @Email:dazhi@dtstack.com
 * @Description:
 */
public class ScheduleEngineProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.project_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.uic_tenant_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Long uicTenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.app_type
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Integer appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.project_name
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.project_alias
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private String projectAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.project_Identifier
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private String projectIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.project_desc
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private String projectDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.status
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.create_user_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.gmt_create
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.gmt_modified
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_engine_project.is_deleted
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_engine_project
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.id
     *
     * @return the value of schedule_engine_project.id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.id
     *
     * @param id the value for schedule_engine_project.id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.project_id
     *
     * @return the value of schedule_engine_project.project_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.project_id
     *
     * @param projectId the value for schedule_engine_project.project_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.uic_tenant_id
     *
     * @return the value of schedule_engine_project.uic_tenant_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Long getUicTenantId() {
        return uicTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.uic_tenant_id
     *
     * @param uicTenantId the value for schedule_engine_project.uic_tenant_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setUicTenantId(Long uicTenantId) {
        this.uicTenantId = uicTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.app_type
     *
     * @return the value of schedule_engine_project.app_type
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Integer getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.app_type
     *
     * @param appType the value for schedule_engine_project.app_type
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setAppType(Integer appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.project_name
     *
     * @return the value of schedule_engine_project.project_name
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.project_name
     *
     * @param projectName the value for schedule_engine_project.project_name
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.project_alias
     *
     * @return the value of schedule_engine_project.project_alias
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public String getProjectAlias() {
        return projectAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.project_alias
     *
     * @param projectAlias the value for schedule_engine_project.project_alias
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setProjectAlias(String projectAlias) {
        this.projectAlias = projectAlias == null ? null : projectAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.project_Identifier
     *
     * @return the value of schedule_engine_project.project_Identifier
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public String getProjectIdentifier() {
        return projectIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.project_Identifier
     *
     * @param projectIdentifier the value for schedule_engine_project.project_Identifier
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setProjectIdentifier(String projectIdentifier) {
        this.projectIdentifier = projectIdentifier == null ? null : projectIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.project_desc
     *
     * @return the value of schedule_engine_project.project_desc
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public String getProjectDesc() {
        return projectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.project_desc
     *
     * @param projectDesc the value for schedule_engine_project.project_desc
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc == null ? null : projectDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.status
     *
     * @return the value of schedule_engine_project.status
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.status
     *
     * @param status the value for schedule_engine_project.status
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.create_user_id
     *
     * @return the value of schedule_engine_project.create_user_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.create_user_id
     *
     * @param createUserId the value for schedule_engine_project.create_user_id
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.gmt_create
     *
     * @return the value of schedule_engine_project.gmt_create
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.gmt_create
     *
     * @param gmtCreate the value for schedule_engine_project.gmt_create
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.gmt_modified
     *
     * @return the value of schedule_engine_project.gmt_modified
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.gmt_modified
     *
     * @param gmtModified the value for schedule_engine_project.gmt_modified
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_engine_project.is_deleted
     *
     * @return the value of schedule_engine_project.is_deleted
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_engine_project.is_deleted
     *
     * @param isDeleted the value for schedule_engine_project.is_deleted
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_engine_project
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", uicTenantId=").append(uicTenantId);
        sb.append(", appType=").append(appType);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectAlias=").append(projectAlias);
        sb.append(", projectIdentifier=").append(projectIdentifier);
        sb.append(", projectDesc=").append(projectDesc);
        sb.append(", status=").append(status);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_engine_project
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduleEngineProject other = (ScheduleEngineProject) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
                && (this.getUicTenantId() == null ? other.getUicTenantId() == null : this.getUicTenantId().equals(other.getUicTenantId()))
                && (this.getAppType() == null ? other.getAppType() == null : this.getAppType().equals(other.getAppType()))
                && (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
                && (this.getProjectAlias() == null ? other.getProjectAlias() == null : this.getProjectAlias().equals(other.getProjectAlias()))
                && (this.getProjectIdentifier() == null ? other.getProjectIdentifier() == null : this.getProjectIdentifier().equals(other.getProjectIdentifier()))
                && (this.getProjectDesc() == null ? other.getProjectDesc() == null : this.getProjectDesc().equals(other.getProjectDesc()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
                && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
                && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
                && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_engine_project
     *
     * @mbg.generated Fri Mar 05 10:26:07 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getUicTenantId() == null) ? 0 : getUicTenantId().hashCode());
        result = prime * result + ((getAppType() == null) ? 0 : getAppType().hashCode());
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getProjectAlias() == null) ? 0 : getProjectAlias().hashCode());
        result = prime * result + ((getProjectIdentifier() == null) ? 0 : getProjectIdentifier().hashCode());
        result = prime * result + ((getProjectDesc() == null) ? 0 : getProjectDesc().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }
}
